# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Thu Aug 22 16:51:38 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Steam.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnRefresh = QtGui.QPushButton(self.centralwidget)
        self.btnRefresh.setGeometry(QtCore.QRect(270, 80, 75, 23))
        self.btnRefresh.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/refresh.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRefresh.setIcon(icon1)
        self.btnRefresh.setObjectName("btnRefresh")
        self.btnBrowse = QtGui.QPushButton(self.centralwidget)
        self.btnBrowse.setGeometry(QtCore.QRect(920, 80, 75, 23))
        self.btnBrowse.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/search.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBrowse.setIcon(icon2)
        self.btnBrowse.setObjectName("btnBrowse")
        self.btnMovetoStorage = QtGui.QPushButton(self.centralwidget)
        self.btnMovetoStorage.setGeometry(QtCore.QRect(20, 680, 121, 23))
        self.btnMovetoStorage.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/forward.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMovetoStorage.setIcon(icon3)
        self.btnMovetoStorage.setObjectName("btnMovetoStorage")
        self.btnMovetoSteam = QtGui.QPushButton(self.centralwidget)
        self.btnMovetoSteam.setGeometry(QtCore.QRect(880, 680, 121, 23))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/backward.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMovetoSteam.setIcon(icon4)
        self.btnMovetoSteam.setObjectName("btnMovetoSteam")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(670, 30, 228, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 149, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lneSteamDir = QtGui.QLineEdit(self.centralwidget)
        self.lneSteamDir.setEnabled(False)
        self.lneSteamDir.setGeometry(QtCore.QRect(20, 49, 331, 21))
        self.lneSteamDir.setObjectName("lneSteamDir")
        self.lneRemoteDir = QtGui.QLineEdit(self.centralwidget)
        self.lneRemoteDir.setEnabled(False)
        self.lneRemoteDir.setGeometry(QtCore.QRect(670, 50, 331, 21))
        self.lneRemoteDir.setObjectName("lneRemoteDir")
        self.lbl_FreeSteam = QtGui.QLabel(self.centralwidget)
        self.lbl_FreeSteam.setGeometry(QtCore.QRect(20, 130, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lbl_FreeSteam.setFont(font)
        self.lbl_FreeSteam.setObjectName("lbl_FreeSteam")
        self.lbl_FreeRemote = QtGui.QLabel(self.centralwidget)
        self.lbl_FreeRemote.setGeometry(QtCore.QRect(670, 130, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lbl_FreeRemote.setFont(font)
        self.lbl_FreeRemote.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_FreeRemote.setObjectName("lbl_FreeRemote")
        self.treeGames = QtGui.QTreeWidget(self.centralwidget)
        self.treeGames.setGeometry(QtCore.QRect(20, 160, 981, 511))
        self.treeGames.setIconSize(QtCore.QSize(16, 16))
        self.treeGames.setUniformRowHeights(True)
        self.treeGames.setItemsExpandable(True)
        self.treeGames.setAllColumnsShowFocus(False)
        self.treeGames.setHeaderHidden(False)
        self.treeGames.setExpandsOnDoubleClick(True)
        self.treeGames.setObjectName("treeGames")
        self.treeGames.header().setVisible(True)
        self.treeGames.header().setDefaultSectionSize(150)
        self.treeGames.header().setHighlightSections(True)
        self.treeGames.header().setStretchLastSection(True)
        self.lbl_Progress = QtGui.QLabel(self.centralwidget)
        self.lbl_Progress.setGeometry(QtCore.QRect(310, 680, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lbl_Progress.setFont(font)
        self.lbl_Progress.setObjectName("lbl_Progress")
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(430, 680, 181, 23))
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 19))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.action_Exit = QtGui.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Legend = QtGui.QAction(MainWindow)
        self.action_Legend.setObjectName("action_Legend")
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.action_Legend)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.action_About)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.action_Exit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lneSteamDir, self.btnRefresh)
        MainWindow.setTabOrder(self.btnRefresh, self.btnBrowse)
        MainWindow.setTabOrder(self.btnBrowse, self.btnMovetoStorage)
        MainWindow.setTabOrder(self.btnMovetoStorage, self.btnMovetoSteam)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "SteamMover", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRefresh.setText(QtGui.QApplication.translate("MainWindow", "   Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowse.setText(QtGui.QApplication.translate("MainWindow", "   Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMovetoStorage.setText(QtGui.QApplication.translate("MainWindow", "    Move to Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMovetoSteam.setText(QtGui.QApplication.translate("MainWindow", "  Move to Steam", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Select a folder for remote storage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Steam Install Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_FreeSteam.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_FreeRemote.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.treeGames.setSortingEnabled(False)
        self.treeGames.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Game", None, QtGui.QApplication.UnicodeUTF8))
        self.treeGames.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.treeGames.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Progress.setText(QtGui.QApplication.translate("MainWindow", "Moving Files...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("MainWindow", "&Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setStatusTip(QtGui.QApplication.translate("MainWindow", "Display the About dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setText(QtGui.QApplication.translate("MainWindow", "&Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Exit the application", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Legend.setText(QtGui.QApplication.translate("MainWindow", "&Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Legend.setStatusTip(QtGui.QApplication.translate("MainWindow", "Legend to explain the meaning of the icons.", None, QtGui.QApplication.UnicodeUTF8))
